#!/bin/bash

# Use this command just as you would `yarn`.
# Examples:
#
#    ./yarn.sh help
#    ./yarn.sh i                 # Install dependencies locally using package-lock.json
#    ./yarn.sh run eslint
#    ./yarn.sh i -E -D "eslint"  # Install the eslint package as a dev-only dep
#    ./yarn.sh i -E "react"      # Install the react package as a dep

docker run --rm \
    -it \
    -v "$(pwd)":/code \
    -w /code \
    --entrypoint yarn \
    node:14.15.1-slim \
    "$@"
