name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Install modules
        run: pnpm install --frozen-lockfile

      - name: Run build
        run: pnpm run build

      - name: Run ESLint
        run: pnpm run eslint
